// src/lib/components/Inventory.svelte
<script>
    import { gameState } from '$lib/game-state.js';
</script>

<div class="inventory">
    <h2>Inventário</h2>
    {#if Object.keys($gameState.player.inventory).length === 0}
        <p>Vazio</p>
    {:else}
        <ul>
            {#each Object.entries($gameState.player.inventory) as [item, quantity]}
                <li>{item.replace(/_/g, ' ')}: {quantity}</li>
            {/each}
        </ul>
    {/if}
</div>

<style>
    .inventory {
        border: 1px solid #ccc;
        padding: 1rem;
        border-radius: 8px;
        background-color: #f9f9f9;
    }
    ul {
        list-style-type: none;
        padding: 0;
    }
</style>

// src/components/Inventory.jsx
import { useGameState } from '../contexts/GameStateContext';

export default function Inventory() {
    const { gameState } = useGameState();
    const inventory = gameState.player.inventory;

    return (
        <div className="widget">
            <h2>Inventário</h2>
            {Object.keys(inventory).length === 0 ? (
                <p>Vazio</p>
            ) : (
                <ul>
                    {Object.entries(inventory).map(([item, quantity]) => (
                        <li key={item}>
                            {item.replace(/_/g, ' ')}: {quantity}
                        </li>
                    ))}
                </ul>
            )}
        </div>
    );
}
